### ISSUE TITLE
artwork bug when using spotify

### ISSUE THREAD

**Issue by elmattt** [thlucas1/homeassistantcomponent_soundtouchplus#17] opened 2024-04-03 15:45 UTC
## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1472
Downloaded Repositories | 24
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 8 août 2024 à 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
instance_id | f20704f83c404a12bc56555d3eb58cd7
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 219.4 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.1), Duck DNS (1.16.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Terminal & SSH (9.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 28
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 mars 2024 à 18:40
-- | --
current_recorder_run | 2 avril 2024 à 19:59
estimated_db_size | 664.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled SmartInspect debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/thlucas1/homeassistantcomponent_soundtouchplus/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

artwork bug when using spotify. the artwork of the first song is displayed and never change after ... only the name of the song change.

when using the official integration for sountouch, it works ...

tested with last version of HA and soundtouch plus integration

### Reproduction steps

1.
2.
3.
...
                            

### Debug logs

```text
## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1472
Downloaded Repositories | 24
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 8 août 2024 à 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
instance_id | f20704f83c404a12bc56555d3eb58cd7
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 219.4 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.1), Duck DNS (1.16.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Terminal & SSH (9.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 28
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 mars 2024 à 18:40
-- | --
current_recorder_run | 2 avril 2024 à 19:59
estimated_db_size | 664.19 MiB
database_engine | sqlite
database_version | 3.44.2

</details>
```

**Comment by thlucas1** [comment] 2024-04-03 17:51
Thanks for the report.  You said that "_when using Spotify, the artwork of the first song is displayed and never changes after - only the name of the song changes_".  

Does this happen for the same song (or playlist)?  If so, what is the Spotify URI song / playlist id.  I'm looking for a way to re-produce the issue, without requesting that you turn on SmartInspect logging for a long period of time.

**Comment by elmattt** [comment] 2024-04-08 11:40
apparently the last update fix the problem ! thanks

**Comment by thlucas1** [comment] 2024-04-08 11:50
Glad to hear it's working.  Thanks for the update - will close this issue.

**Closed by thlucas1** 2024-04-08 11:50 UTC

**Comment by thlucas1** [comment] 2024-04-15 20:11
@elmattt 
I was finally able to reproduce the artwork issue with the SoundTouchPlus integration not displaying the correct artwork image when playing Spotify content; as it turns out, it was not fixed as I had thought.  I just pushed v1.0.40 of the SoundTouchPlus integration to really fix it.

Prior to the fix, the artwork image url that was being used came from the ContentItem ContainerArt value, which in MOST cases matches the currently playing ArtUrl value which matches the Artist / Album / Track value; there are some use cases (Spotify being one) where the ContentItem ContainerArt url does not match the ArtUrl value though - in these cases, the ArtUrl value should be returned instead, as it matches the Artist / Album / Track name being played.  

This manifested itself when you start playing a Spotify playlist, and play extends beyond the last track in the playlist.  The ContentItem ContainerArt value remains set at the last playlist item played, but the current Artist / Album / Track / ArtUrl values are the currently playing track, which is "intelligently" selected by Spotify based on your play history.

Just thought you would want to know.

**Comment by elmattt** [comment] 2024-04-16 14:34
ohh nice, thanks for the update, no problem for me with this update !
